version: 2.1
jobs:
  build_n_run:
    parameters:
      python_version:
        type: string
      mongo_version:
        type: string
      mengine_version:
        type: string
    docker:
      - image: circleci/<<parameters.python_version>>
      - image: circleci/<<parameters.mongo_version>>
    environment:
      JOB_VERSION: <<parameters.python_version>>_<<parameters.mongo_version>>_<<parameters.mengine_version>>
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}-{{ .Environment.CIRCLE_JOB }}
      - when:
          condition:
            and:
              - not:
                  equal: [ "mongoengine==0.16.3", <<parameters.mengine_version>> ]
          steps:
            - run:
                name: Updating MongoEngine version
                command: |
                  poetry add "<<parameters.mengine_version>>" "pymongo>=3.6.1"
      - run:
          name: Poetry installing dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run tests & coverage
          command: |
            poetry run pytest \
              --cov=mongoengine_softdelete \
              --cov-report html:tests_coverage/$JOB_VERSION/pycov \
              --html="tests_coverage/$JOB_VERSION/coverage.html" --self-contained-html \
              --junit-xml="tests_coverage/$JOB_VERSION/coverage.xml"
            poetry run coverage report
            mv .coverage tests_coverage/$JOB_VERSION/
      - when:
          condition:
            and:
              - equal: [ "mongoengine==0.16.3", <<parameters.mengine_version>> ]
              - equal: [ "mongo:3.6", <<parameters.mongo_version>> ]
              - equal: [ "python:3.7", <<parameters.python_version>> ]
          steps:
            - run:
                name: Using this coverage report for Codacy
                command: |
                  cp tests_coverage/$JOB_VERSION/coverage.xml tests_coverage/coverage.xml
      - persist_to_workspace:
          root: ~/
          paths:
            - project/tests_coverage
      - run:
          name: Build
          command: |
            make build
  store_coverage:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      # - run :
      #     name: Upload coverage results to Codacy
      #     command: |
      #       pip install --upgrade codacy-coverage
      #       cd ~/project
      #       python-codacy-coverage -r ~/project/tests_coverage/coverage.xml
      - store_artifacts:
          path: ~/project/tests_coverage/
      - store_test_results:
          path: ~/project/tests_coverage/

workflows:
  version: 2.1
  all-tests:
    jobs:
      - build_n_run:
          matrix:
            parameters:
              python_version:
                - "python:3.7"
                - "python:3.8"
                # - "python:3.9"
              mongo_version:
                - "mongo:3.6"
                # - "mongo:4.4"
              mengine_version:
                - "mongoengine==0.16.3"
                # - "mongoengine@^0.17.0"
                # - "mongoengine@^0.18.0"
                # - "mongoengine@^0.19.0"
                # - "mongoengine@^0.20.0"
                # - "mongoengine@^0.21.0"
                # - "mongoengine@^0.22.0"
                # - "mongoengine@^0.23.0"
      - store_coverage:
          requires:
            - build_n_run
