version: 2.1
executors:
    docker:
      - image: circleci/python:3.7
      - image: circleci/mongo:3.6
jobs:
  build_n_run:
    parameters:
      mongo_version:
        type: string
      python_version:
        type: string
    docker:
      - image: circleci/python:<<parameters.python_version>>
      - image: circleci/mongo:<<parameters.mongo_version>>
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install poetry
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run tests
          command: |
            poetry run pytest \
              --html=tests_coverage/coverage.html --self-contained-html \
              --junit-xml=tests_coverage/coverage.xml
      - persist_to_workspace:
          root: ~/
          paths:
            - project/tests_coverage
      - run:
          name: Build
          command: |
            make build

  upload-coverage:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - store_artifacts:
          path: ~/project/tests_coverage/
      - store_test_results:
          path: ~/project/tests_coverage/

workflows:
  version: 2.1
  all-tests:
    jobs:
      - build_n_run:
          matrix:
            parameters:
              mongo_version: [3.6, 4.4]
              python_version: [3.7]
      - upload-coverage:
          requires:
            - build_n_run
